elibs/ebash

share/efuncs.sh

So that you can use die for things like wrong parameter values, etc... you don't want a stacktrace for that.

add param to die to suppress the stacktrace

---

bin/ebash
bin/iebash
changelog.md
unittest/process.etest

This enhances ebash so that it can function as actual shebang. e.g. instead of the old:
```
#!/usr/bin/env bash
$(ebash --source)
<rest of script>
```
You can now simply say:
```
#!/usr/bin/env ebash
<rest of script>
```

Enhance ebash to function properly as top-level shebang.

---

bin/ebash
bin/etest
share/cgroup.sh
share/ebash.sh
share/efuncs.sh
unittest/ebash_bin_sh
unittest/ebash_interpreter

@ericpe  pointed out that if you call a bash script via `sh` that it is put into POSIX mode. That's the issue! POSIX mode basically disables all the things ebash needs. I added a unit test before I fixed this and indeed was able to easily reproduce this. Basically just added a `set +o posix` to turn posix mode off. Unit test passes now.

Fixes #17 by disabling posix mode.

---

bin/bashlint
bin/ebash
bin/elint
share/emsg.sh
unittest/ebash.etest
unittest/emsg.etest

This fixes #26 by adding new option flags to ebash to make it less onerous to setup some default settings. I like option flags better than env variables as they are more transparent what we're doing, show up in usage statements and logs, etc. env variables are just to opaque.
This adds 
```
--color
--interactive
--msg-prefix
```
Now you can say
```
$(/liqid/ebash/bin/ebash --source --color --interactive --msg-prefix=time)
```
I also changed `etimestamp` to use `RFC3339` by default everywhere. The only way to get the old behavior is to set new `ETIMESTAMP_FORMAT=StampMilli` vs the new default `RFC3339`. But honestly, `RFC3339` is really what we should be using everywhere by now.

Ebash color mode

---

README.md
bin/ebash
bin/ebash-repl
bin/etest
share/opt.sh
unittest/opt.etest

This closes issue #24 by adding a new opt_parse type of `=` which is a required, non-empty string parameter. Also updates usage statements to show required options in `(...)` and annotate them with `(*)` in usage statement.
Also updates README and related tests.

Opt nonempty string

---

bin/ebash
share/opt.sh

This is not a very big change but it cleans up the output from `--help` / `-?` to have a bit more structure to it with section headers for `DESCRIPTION` and `OPTIONS` and `ARGUMENTS` similar to a a README. Also changes ebash documentation into an opt_usage string.

Structure usage statement from opt --help/-?

---

.github/workflows/Pipeline.yml
Makefile
share/dialog.sh
unittest/dialog.etest
unittest/opt.etest

This changes dialog_prompt to automatically replace underscores with spaces in the labels. It also uppercases each word.
But it takes it further and provides a new `--transform` accumulator (which means you can provide it multiple times and it builds them up into an array) of sed style expressions to be applied to the labels. This way you can customize the behavior of the label replacements as needed.

Add new transform option flag to dialog. Also automatically replace underscores

---

share/dialog.sh
share/signal.sh
unittest/dialog.etest

SO many fixes to dialog layer:
- Remove export and global flags in dialog_prompt as it's not needed
- Instead add new declare option flag. Allowing caller to opt-out of variable declaration.
- MASSIVE fixes to flow of tab through interface. When you hit tab it now goes to OK button
instead of EDIT to avoid a double-tab at the end.
- When you hit the last field in the input window, if you hit down arrow it takes you down
to the OK/Edit/Cancel buttons.

Dialog fixes

---

share/etable.sh
share/pack.sh
unittest/etable.etest

Adds new `etable_values` function to make it super simple to create an etable using a simple list of variables to generate a key/value table. Also seamlessly supports arrays, associative arrays, and packs (with required '%' in front of pack variable name).
Operates on variables only similar to `ebanner` and `lval`. !! So much safer and easier to use.
Also supports sorting the keys, uppercase them, and lowercasing them!

Addresses ebash issue 4 to add new etable_values function.

---

bin/etest
bin/selftest
selftest/hang.etest
selftest/hang_override.etest
selftest/hang_standalone

This adds a couple of new parameters to etest : `--timeout` for per-test timeout and `--total-timeout` for total test timeout for all tests that are executed. You can also override the test timeout programmatically in a test setup() via new `ETEST_TIMEOUT` variable

Suppress output from test watcher.

---

share/emock.sh
tests/emock.etest

@thecodenomad found so many bugs! Love you Ray.
As you noted, the `called` file wasn't reflecting the right call count. There were many bugs I found while doing some TDD and really hardening the hell out of this. The most important are:
1. Holy hell, I disabled fatal error handling inside the mock, but didn't do it in a subshell, so this affected entire etest environment. Which was making failures in all the tests after this. WOW. NOOB.
2. Obviously, we were incrementing `called` file incorrectly. On the first call we would write out `0` into called instead of `1`. The tests were not detecting this because of (1).
3. All the code that looked up the last called value to get the number to use if not explicitly passed in were also off by one. Gah. I added a new function `emock_indexes` which …

Wow, this was a real mess. Thanks Ray for finding it!

---

share/daemon.sh
share/docker-overlay/systemd/usr/local/bin/systemctl
tests/daemon.etest
tests/docker.etest

This adds support to ebash daemons to mark a daemon as enabled or not. This will allow us to support the systemctl idiom of `systemctl enable --now <service>` and `systemctl disable --now <service>` more naturally. For ebash daemon purposes we're not _really_ making use of this flag. But we're allowing the caller's init script to make use of it. For example, you can send SIGTERM or mock out reboots in a docker container and the init script could then decide to start the daemons or not based on if they are enabled. This is all for the caller to use as they see fit.

Add enabled support to daemon module and systemctl wrapper.

---

share/trap.sh
tests/trap.etest

Bo found an issue where if we call `trap_add` with an explicit list of signals it was compounding the command that would get run. e.g. if you ran 
`trap_add "echo foo" SIGUSR1 SIGUSR2` 
then you'd end up executing a command of `echo foo` for `SIGUSR1`. But unexpectedly `echo foo; echo foo` for `SIGUSR2`.
This is because we were not initializing the `complete_trap` variable properly.
I also found sometimes we'd end up with syntax errors in the final command due to silly things like `echo foo; ;` where the second command of `; ;` is not legal bash syntax. Making it an array maid it simpler to manipulate the command we're building up.
Added some new tests to validate the new behavior.
BTW, I started down the path of adding some more powerful `trap_pop` functionality but it got complicated …

Fix trap_add to deal with multiple signals properly and do not register multiple

---

bin/etest
share/cgroup.sh
share/emock.sh
tests/cgroup.etest

Well, this was far from easy to track down. But I'm glad I did as this has been plaguing me in various scenarios for ages and I couldn't ever pin this down.
The gist of the problem is that the background processes we launch for `elogfile` (which is what captures all our test output into a logfile in .work directory) were being incorrectly considered process leaks. The fix is in `global_setup` to explicitly move those pids into our parent `ETEST_CGROUP` before we start running all our tests.
Each test gets run in its own child cgroup under `ETEST_CGROUP`. And for some unknown reasons, on some older Linux distros, the original elogfile pids were incorrectly showing up under that cgroup which caused the tests to sometimes fail due to a false positive as a process leak.
The huge upside to …

Etest pidleak

---

install/depends
share/pkg.sh

I want to speed up package installation on MacOS. It is slow b/c with brew you get an error if you try to install a package that is already installed. The brew developers refuse to fix this and say it is by design. Their solution to this is `brew bundle` which gracefully handles this situation.
So this changes ebash over to use `brew bundle`. It's dramatically faster when frequently installing a lot of already installed packages. Takes less than a second vs a couple minutes.

Use brew bundle to speed up installs on MacOS.

---

share/cicd.sh
tests/cicd.etest

The CI/CD versioning ebash creates is not semver compliant (https://semver.org/). Semver only officially supports 3 octets -- major.minor.patch. And more importantly, Go only supports 3 octets. So I'm changing ebash CI/CD versioning to also be semver compliant.

Change CI/CD code to be semver compliant with major.minor.patch.

---

share/conf.sh
tests/conf.etest

This adds `conf_to_json` to convert a named configuration to an anonymous JSON object. Each named section in the configratuion will be a top-level named JSON object. Each property inside that section will then be a series of `'"key": "value"'` pairs in the JSON. 
By default, all the properties are displayed as quoted strings. But this can be controlled via `--props-int` to not quote the values as they are known to be integers. Alternatively the properties can be automatically split on whitespace and printed as a JSON array using `--props-array`.
For some detailed examples see `tests/conf.etest`:
* ETEST_conf_to_json
* ETEST_conf_to_json_int
* ETEST_conf_to_json_array

Add new conf_to_json to easily convert a conf map to structured JSON

---

install/nodejs
tests/nodejs_install.etest

Well, it's hard to use glib binaries on a musl system. Nodejs install will use alpine's default package instead of the available binary.

Nodejs fixes

---

install/nodejs
tests/nodejs_install.etest

Internally this script was referencing a filepath instead of a folder path.

Fix conflation of path and filename in nodejs install.

---

docker/Dockerfile.build
docker/setup
install/go
install/shellcheck
share/checkbox.sh
share/docker.sh
tests/all_depends.etest
tests/docker.etest

This adds a new convenience wrapper around `docker_compose` to make our lives a lot easier. From the docs, here is what it does:
`docker_compose_run` is an intelligent wrapper around vanilla `docker-compose` which integrates nicely with ebash. In
addition to the normal additional error checking and hardening the ebash variety brings, this version provides the
following super useful features:
- Accept a list of environment variables which should be exported into the underlying docker_compose run command. Each
of these variables will be expanded in-place by ebash using `expand_vars`. As such the variables can be a simple list
of env variables to export as in `FOO BAR ZAP` or they can point to other variables as in `FOO=PWD BAR ZAP` or they
can point to string literals as in …

Docker compose

---

.github/workflows/pipeline.yml
Makefile
doc/compatibility.md
install/go
share/docker.sh
tests/docker.etest

This is an enhancement to the new `docker_compose_run` in ebash so that in manticore repo we can tail the output of all the docker containers rather than just `sftp` when we do a `make run`

Add new --follow-all flag to docker_compose_run.

---

share/docker.sh
tests/docker.etest

This adds optional SSH Port Forwarding support into ebash's provided `docker_run` and `docker_compose_run`. This will help when using a docker context that points to a remote docker server. This can be done with `docker context` or with `DOCKER_HOST` or with `DOCKER_CONTEXT`. All of this funnels down into `docker context` implementation. So we can directly query docker context to see what the host we are talking to is and see if it's a remote SSH server.
This will make it really simple in manticore I can say `docker_compose_run --ssh-port-forward 2222 --ssh-port-forward 9090` and then do an `sftp -P 2222 root@localhost`.

Docker ports

---

share/docker.sh
tests/docker.etest

Harden ebash docker_compose_run to more aggressively cleanup after containers

Add docker-compose kill call to more aggressively kill and cleanup containers

---

.github/workflows/pipeline.yml
share/opt.sh
tests/opt.etest

This just gracefully exits immediately at the top of `opt_parse` if `nullglob` is enabled. I tried just disabling it directly, but that doesn't work at all. In any event, I really don't see a need for `nullglob` so I think it's acceptable to just bail immediately. It's sure beats the infinite recursion mess we're getting now.

Immediately fail opt_parse gracefully if nullglob is enabled.

---

share/etest/assert.sh
share/etest/options.sh
tests/pkg.etest

Allow disabling checking for process and mount leaks. Useful for when you're running in a container and it's not desired.

Disable checks

---

share/ebash.sh
tests/all_depends.etest

Remove need for `ps` to be installed to check for BASH env.

Avoid need for ps in ebash.sh.

---

share/etest/runners.sh

The current implementation of `suite_teardown` callback iscalled after `etest` runs through all test cases. However, if the `failfast` is enabled and a test case does not pass, the test aborts without calling the `suite_teardown` callback.
This PR reimplements `suite_teardown` mechanism so that it will be triggered at the end of the test, for all following scenario:
1. All tests passes
2. Some tests fails without `failfast` enabled
3. Test aborted when a test fails with failfast `enabled`
4. Test aborted by receiving an interrupt.

Reimplement suite_teardown mechanism

---

bin/etest
doc/debugging.md
share/archive.sh
share/ebash.sh
share/emsg.sh
share/etest/options.sh
share/etest/results.sh
share/etest/runners.sh
share/etest/test_list.sh
share/opt.sh
tests/etest/options/config_file.etest
tests/etest/results/summary.etest

A number of improvements to etest:
1. Create a `status.json` file in the logdir that gets updated after every test. This includes useful things like percent complete, failed tests, etc.
2. Add new `--destroy` flag to etest to make it easier to aggressively kill all etest instances on the system.
3. Add new `--silent` flag to make etest totally silent (as much as possible)
4. Create new `options.json` file in logdir with the options used on that test iteration.
5.

Status json
